# Generated by Django 3.0.7 on 2020-06-27 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_name', models.CharField(max_length=200, unique=True, verbose_name='Покемон')),
                ('residence', models.EmailField(max_length=200, verbose_name='Проживає')),
                ('description', models.CharField(max_length=600, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pokemon_type', models.IntegerField(choices=[(1, 'Nature'), (2, 'Water'), (3, 'Fire'), (4, 'Electricity'), (5, 'Earth'), (6, 'Air'), (7, 'Telecinesis'), (8, 'Darkness'), (9, 'Light'), (10, 'Ice'), (11, 'Cosmic'), (12, 'Time')], verbose_name='Тип покемона')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
