# Generated by Django 3.0.7 on 2020-06-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200627_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompokemon',
            name='residence',
            field=models.CharField(max_length=200, verbose_name='Проживає'),
        ),
    ]
