# Generated by Django 3.0.7 on 2020-06-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200627_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompokemon',
            name='residence',
            field=models.CharField(max_length=200, verbose_name='Де знайти'),
        ),
        migrations.AlterField(
            model_name='custompokemon',
            name='trainer',
            field=models.CharField(max_length=200, verbose_name='Тренер'),
        ),
    ]
