# Generated by Django 3.0.7 on 2020-06-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200627_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custompokemon',
            old_name='created_at',
            new_name='catched_up_in',
        ),
    ]
