# Generated by Django 3.0.7 on 2020-06-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200627_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompokemon',
            name='evolution_form',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1, verbose_name='Форма еволюції'),
            preserve_default=False,
        ),
    ]
