# Generated by Django 3.0.7 on 2020-07-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200627_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompokemon',
            name='evolution_form',
            field=models.IntegerField(choices=[(0, 'non evolving pokemon'), (1, '1'), (2, '2'), (3, '3')], verbose_name='Форма еволюції'),
        ),
    ]
